files: ^(agent/|mcp_server/|cli/|argocd/)

repos:
  - repo: https://github.com/google/yamlfmt
    rev: v0.12.1
    hooks:
      - id: yamlfmt

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        # Argumentos para garantir compatibilidade com o Black (linha max = 88 e ignorar regras conflitantes)
        args: ["--max-line-length=88", "--extend-ignore=E203,W503"]
