{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "nvd-mcp.fullname" . }}
  labels:
    {{- include "nvd-mcp.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.store.name }}
    kind: {{ .Values.externalSecret.store.kind }}
  target:
    name: {{ include "nvd-mcp.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: NVD_API_KEY
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: {{ .Values.externalSecret.remoteRef.property }}
{{- end }}
